### ISSUE TITLE
Several "Clone failed" errors when downloading assignment

### ISSUE THREAD

**Issue by palves-ulht** [education/classroom-assistant#113]
When I ask Classroom Assistant to download all the repositories, I get this error for several repositories and it remains stuck (I have to cancel):

![image](https://user-images.githubusercontent.com/10359239/46960318-2e952c00-d096-11e8-87db-0506bb1b08e7.png)

As you can see, there are errors in only some of them.
Strangely enough, all the repositories seem to have been successfully cloned to my disk (even those with the error).

Is there a log file where I can see more information about these errors?

I'm running Classroom Assistant (v.1.0.2) on MacOS High Sierra.

**Comment by johndbritton** [comment]
@palves-ulht This is a known issue and we are currently working on a fix.

It is caused by one or more of the admins on your GitHub account de-authorizing GitHub Classroom. A workaround is to remove those other admins from your organization or have them reauthorize classroom.

See: https://github.com/education/classroom-assistant/issues/110

**Comment by palves-ulht** [comment]
@johndbritton Thanks for the quick reply. 
However, I am the only administrator of this classroom:
![image](https://user-images.githubusercontent.com/10359239/46961497-cd228c80-d098-11e8-8044-39966731a65f.png)

It is true that my organization has another member but I am the only owner.

**Comment by johndbritton** [comment]
Seems I may have spoken too soon. @srinjoym Can you investigate this issue more closely?

**Comment by srinjoym** [comment]
@palves-ulht Thanks for writing in! Super sorry you're hitting this issue, the problem looks to be on the Classroom side, so we'll get a fix out ASAP. For now, the app should continue to clone all of your student's submissions correctly it will just show an error on the UI.

@johndbritton @BenEmdon This issue looks like it's related to https://github.com/education/classroom/issues/1646

Classroom Assistant is receiving multiple submissions with the same `id` from Classroom. It clones it down successfully for the first one, and then errors on the second one since it has already cloned it into that folder.

Do we have a fix for Classrooms that are already in this state?

**Comment by BenEmdon** [comment]
The fix I made in https://github.com/education/classroom/issues/1646 will ensure that duplicate `AssignmentRepo`s aren't made in the future.

We might be able to run a rake task to delete duplicate assignment repos. 
This could be unsafe since it's not always easy to determine which `AssignmentRepo` a student has started working in. We definitely don't want to delete an `AssignmentRepo` that a student has started working in.

**Comment by palves-ulht** [comment]
> @palves-ulht Thanks for writing in! Super sorry you're hitting this issue, the problem looks to be on the Classroom side, so we'll get a fix out ASAP. For now, the app should continue to clone all of your student's submissions correctly it will just show an error on the UI.

Although I thought initially that the app was cloning all the submissions, I'm afraid that's not the case. I have an assignment where classroom assistant tells me that I have 59 submissions. Of those, 5 are duplicates, so I have 54 submissions. Just to confirm, I checked classroom.github.com and it matches (54 submissions). So, the first issue is that classroom assistant is duplicating some entries.

But the most worrying issue is that when I tell the app to clone all the submissions, it only clones 39 (btw, the number of "Clone failed" messages in the UI doesn't match these numbers either). Actually, I don't know if this is related to the current "Clone failed" issue. If it's a different issue, I can create one. And please let me know if you need further information.

**Comment by palves-ulht** [comment]
I can confirm that the problem is solved! Thanks!

**Comment by math-mcshane** [comment]
Just want to follow up -- @BenEmdon -- this issue appears to have returned (?). I am getting the same mixture of error messages/successes as OP. Apologies if this has been posted elsewhere. 

As an example repo: 
https://classroom.github.com/classrooms/79130288-stat375-sp21/assignments/journal-1
