### ISSUE TITLE
Cloned repos from classroom assistant shouldn't be read only

### ISSUE THREAD

**Issue by zamansky** [education/classroom-assistant#155]
When cloning a set of assignments using classroom assistant, they're read only:

   remote: Temporary clone tokens are read-only.

That means a teacher can't annotate, add, or modify anything and then push it back to the student. 

One can work directly in the assignment repo on GitHub or clone it directly from there but when operating on a class of assignments it would much more efficient to be able to work from the command line.

This came up for me while grading a GitHub classroom based exam and wanting to add notes to each submission and then push them back to my students.

**Comment by d12** [comment]
:wave: @zamansky , this issue is being tracked here: https://github.com/education/classroom-assistant/issues/103. This comment https://github.com/education/classroom-assistant/issues/103#issuecomment-443136565 has a workaround that may work for you. It's repetitive, but it'll allow you to push and pull to these repositories.

We're hoping to have a better solution in place at some point, that issue will be updated when we make progress.

Closing this one as a duplicate
